import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function fixture(storage={getItem:()=>null,setItem:()=>{}}){const s={window:{},localStorage:storage};vm.createContext(s);for(const f of ['theories.js','workspace.js'])vm.runInContext(fs.readFileSync(f,'utf8'),s);return s.window.QI_WORKSPACE;}
test('workspace round trip preserves notes, bookmarks, read entries and comparisons',()=>{let raw;const storage={getItem:()=>raw,setItem:(k,v)=>raw=v};const w=fixture(storage),data=w.data;data.bookmarks=['unruh'];data.read=['unruh'];data.notes.unruh='<script>literal text</script>';data.comparisons=[{name:'Horizon comparison',theoryIds:['unruh','hawking-radiation']}];assert.equal(w.save(data),true);assert.deepEqual(JSON.parse(JSON.stringify(fixture(storage).data)),JSON.parse(raw));});
test('workspace rejects malformed, oversized and unknown-entry records without replacing saved data',()=>{const w=fixture();for(const bad of [null,{version:2},{...w.data,bookmarks:['unknown']},{...w.data,notes:{unruh:'x'.repeat(20001)}},{...w.data,comparisons:[{name:'one',theoryIds:['unruh']}]}])assert.throws(()=>w.validate(bad));assert.equal(w.data.bookmarks.length,0);});
test('import merges without overwriting different existing notes',()=>{const w=fixture(),a=w.data;a.notes.unruh='Original';w.save(a);const b=w.data;b.notes.unruh='Imported';b.bookmarks=['unruh'];assert.equal(w.merge(b),true);assert.match(w.data.notes.unruh,/Original[\s\S]*Imported/);assert.equal(w.data.bookmarks.length,1);});
test('quota failures and corrupt stored data are reported without silent data loss',()=>{let writes=0;const w=fixture({getItem:()=>'{bad',setItem:()=>{writes++;throw Error('quota');}});assert.match(w.error,/not been overwritten/);assert.equal(writes,0);const d=w.data;d.notes.unruh='unsaved';assert.equal(w.save(d),false);assert.match(w.error,/not be saved/);assert.equal(w.exportText(),'{bad');assert.equal(writes,0);assert.equal(w.data.notes.unruh,undefined);});

test('a quota error never changes the saved in-memory state',()=>{const w=fixture({getItem:()=>null,setItem:()=>{throw Error('quota');}});const data=w.data;data.notes.unruh='Draft';assert.equal(w.save(data),false);assert.match(w.error,/not saved/);assert.equal(w.data.notes.unruh,undefined);});
test('exported JSON can be imported into a fresh workspace and repeated imports are idempotent',()=>{const a=fixture(),first=a.data;first.notes.unruh='First';a.save(first);const imported=a.data;imported.notes.unruh='Second';a.merge(imported);const once=a.exportText();a.merge(imported);assert.equal(a.exportText(),once);const b=fixture();b.merge(JSON.parse(once));assert.equal(b.exportText(),once);});
test('workspace size limit counts UTF-8 bytes and keeps failed merges atomic',()=>{const w=fixture(),data=w.data;const s={window:{}};vm.createContext(s);vm.runInContext(fs.readFileSync('theories.js','utf8'),s);for(const t of s.window.QI_DATA.theories.slice(0,30))data.notes[t.id]='界'.repeat(19000);assert.equal(w.save(data),false);assert.match(w.error,/1 MB/);assert.equal(Object.keys(w.data.notes).length,0);const long=w.data;long.notes.unruh='x'.repeat(20000);w.save(long);const incoming=w.data;incoming.notes.unruh='y';assert.throws(()=>w.merge(incoming));assert.equal(w.data.notes.unruh.length,20000);});
